[package]
name = "qtlreaper"
version = "0.1.2"
authors = ["Christian Fischer <christian@chfi.se>"]
edition = "2018"

[dependencies]
rand = "0.6"
structopt = "0.2"
rayon = "1.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"